version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: car_lease_postgres
    environment:
      POSTGRES_USER: carlease_user
      POSTGRES_PASSWORD: carlease_pass
      POSTGRES_DB: car_lease_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
